# Generated by Django 4.2.7 on 2023-11-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_rename_user_userextended'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtended',
            new_name='User',
        ),
    ]
