# Generated by Django 4.2.7 on 2023-11-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='NURSE', max_length=20),
        ),
    ]
