# Generated by Django 4.2.7 on 2023-11-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_contact_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='NURSE', max_length=20),
        ),
    ]
