# Generated by Django 4.2.7 on 2024-04-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_cost_item_expirydate_item_formulation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expirydate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='units',
        ),
    ]
