# Generated by Django 4.2.7 on 2024-04-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_expirydate_remove_item_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
