# Generated by Django 4.2.7 on 2024-04-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('batchno', models.CharField(blank=True, max_length=100)),
                ('date_produced', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('total', models.IntegerField(blank=True, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_batch', to='inventory.item')),
            ],
        ),
    ]
