# Generated by Django 4.2.7 on 2024-04-30 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('units', models.IntegerField()),
                ('being_delivered', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_in_order', to='inventory.batch')),
                ('items', models.ManyToManyField(to='inventory.orderitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odering_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
