# Generated by Django 4.2.7 on 2024-05-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaceorderitem_purchaceorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaceorder',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='purchaceorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchaceorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaceorderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaceorderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PurchaceOrder',
        ),
        migrations.DeleteModel(
            name='PurchaceOrderItem',
        ),
    ]
