# Generated by Django 4.2.7 on 2024-05-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_order_batch_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availableqty',
            field=models.IntegerField(default=0),
        ),
    ]
