# Generated by Django 4.2.7 on 2024-05-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_availableqty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_id_234504_idx',
            old_name='inventory_i_id_a4d623_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_title_24296c_idx',
            old_name='inventory_i_title_ecb3f6_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_created_e283f3_idx',
            old_name='inventory_i_created_9dc880_idx',
        ),
    ]
