# Generated by Django 4.2.7 on 2024-01-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_salutation', models.CharField(max_length=255)),
                ('pt_firstname', models.CharField(max_length=255)),
                ('pt_surname', models.CharField(max_length=255)),
                ('pt_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=2)),
                ('pt_age', models.CharField(max_length=255)),
                ('pt_profession', models.CharField(choices=[('DR', 'Doctor'), ('ENG', 'Engineer'), ('PES', 'Peasant'), ('STU', 'Student')], default='PES', max_length=3)),
                ('pt_contact', models.CharField(max_length=255)),
                ('pt_religion', models.CharField(max_length=255)),
                ('pt_village', models.CharField(max_length=255)),
                ('pt_parish', models.CharField(max_length=255)),
                ('pt_subcounty', models.CharField(max_length=255)),
                ('pt_district', models.CharField(max_length=255)),
                ('pt_nationality', models.CharField(max_length=255)),
                ('pt_nin', models.CharField(max_length=255)),
                ('pt_photo', models.ImageField(blank=True, upload_to='patients/%Y/%m/%d/')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['pt_surname'], name='patients_pa_pt_surn_4e4e00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription', models.CharField(blank=True, max_length=255, null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.patient')),
            ],
        ),
    ]
