# Generated by Django 4.2.7 on 2024-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_encounter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
