# Generated by Django 4.2.7 on 2024-01-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_encounter_options_encounter_labrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('labrequest', models.CharField(blank=True, max_length=255, null=True)),
                ('sampletaken', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=255, null=True)),
                ('requestingdoctor', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('encounterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.encounter')),
                ('identitylab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientid', to='patients.patient')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['identitylab'], name='patients_la_identit_aaced1_idx')],
            },
        ),
    ]
