# Generated by Django 4.2.7 on 2024-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='pt_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='pt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='pt_sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
