# Generated by Django 4.2.7 on 2024-04-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_encounter_pt_age_encounter_pt_name_encounter_pt_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_nin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_parish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_profession',
            field=models.CharField(blank=True, choices=[('DR', 'Doctor'), ('ENG', 'Engineer'), ('PES', 'Peasant'), ('STU', 'Student')], default='PES', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_religion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_salutation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_subcounty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pt_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
