# Generated by Django 4.2.7 on 2024-04-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_encounter_visit_date_alter_labtest_visit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
